/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "syncer.h"
#include <iostream>
#include "ThreadPool.hxx"
#include "CopyTask.hxx"

extern ThreadPool tp;

int *
copy_file_1_svc(CopyInfo *argp, struct svc_req *rqstp)
{
	static int  result;

//	std::cout << "coping " << argp->from << " -> " << argp->to
//                  << (argp->sync ? " sync" : " async") << std::endl;
	result = tp.insertTasks(new CopyTask(argp->from, argp->to));
	return &result;
}
