/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SYNCER_H_RPCGEN
#define _SYNCER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct CopyInfo {
	char *from;
	char *to;
	int sync;
};
typedef struct CopyInfo CopyInfo;


#define SYNCERPROG 0x20000001
#define SYNCERVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define COPY_FILE 1
extern  int * copy_file_1(CopyInfo *, CLIENT *);
extern  int * copy_file_1_svc(CopyInfo *, struct svc_req *);
extern int syncerprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define COPY_FILE 1
extern  int * copy_file_1();
extern  int * copy_file_1_svc();
extern int syncerprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_CopyInfo (XDR *, CopyInfo*);
extern  bool_t xdr_CopyInfo (XDR *, CopyInfo*);

#else /* K&R C */
extern bool_t xdr_CopyInfo ();
extern bool_t xdr_CopyInfo ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SYNCER_H_RPCGEN */
