/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "syncer.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include "ThreadPool.hxx"
#include "CopyTask.hxx"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
syncerprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		CopyInfo copy_file_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case COPY_FILE:
		_xdr_argument = (xdrproc_t) xdr_CopyInfo;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) copy_file_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

#define CP_BUF_SIZE 65536

ThreadPool tp(CP_BUF_SIZE);

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	if (argc != 2) {
		fprintf(stderr, "Usage: %s threads_num\n", argv[0]);
		exit(1);
	}

	pmap_unset (SYNCERPROG, SYNCERVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SYNCERPROG, SYNCERVERS, syncerprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SYNCERPROG, SYNCERVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SYNCERPROG, SYNCERVERS, syncerprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SYNCERPROG, SYNCERVERS, tcp).");
		exit(1);
	}
	tp.start(atoi(argv[1]));
	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
