/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "syncer.h"


void
syncerprog_1(char *from, char *to, int sync)
{
	CLIENT *clnt;
	int  *result_1;
	CopyInfo  copy_file_1_arg = {from, to, sync};
	char *host = "127.0.0.1";

#ifndef	DEBUG
	clnt = clnt_create (host, SYNCERPROG, SYNCERVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = copy_file_1(&copy_file_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	if (argc < 3) {
		printf ("usage: %s path/source path/destination\n", argv[0]);
		exit (1);
	}
	syncerprog_1 (argv[1], argv[2], 0);
exit (0);
}
