/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "syncer.h"

bool_t
xdr_CopyInfo (XDR *xdrs, CopyInfo *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->from, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->to, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->sync))
		 return FALSE;
	return TRUE;
}
