SVN_VERSION  := $(shell svnversion ..)
TAG_VERSION  := $(shell cat ../VERSION)
DATA_VERSION := $(shell cat ../VERSION.LAYOUT)
VERSION = -DSVN_VERSION=$(SVN_VERSION) -DTAG_VERSION=$(TAG_VERSION) \
		  -DDATA_VERSION=$(DATA_VERSION)

#test:
#	@echo $(TAG_VERSION)
#	@echo $(SVN_VERSION)
#	@echo $(DATA_VERSION)
#	@echo $(VERSION)
