#! /bin/tcsh -f

echo "Hey.  You can just use make now"

foreach file ( *.c )
    echo $file
    gcc -fPIC -DHAVE_CONFIG_H -I. -I../../adio/include -DOMPI_BUILDING=1 -I/users/johnbent/openmpi/openmpi-1.3.3/ompi/mca/io/romio/romio/../../../../.. -I/users/johnbent/openmpi/openmpi-1.3.3/ompi/mca/io/romio/romio/../../../../../opal/include -I../../../../../../../opal/include -I../../../../../../../ompi/include -I/users/johnbent/openmpi/openmpi-1.3.3/ompi/mca/io/romio/romio/include -I/users/johnbent/openmpi/openmpi-1.3.3/ompi/mca/io/romio/romio/adio/include -O3 -DNDEBUG -I/opt/panfs/include -finline-functions -fno-strict-aliasing -pthread -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_ROMIOCONF_H -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_ROMIOCONF_H -I../../include -c $file -o $file:r.o 
end
ar -cru ../../../../../../../ompi/mca/io/romio/.libs/libmca_io_romio.a *.o 
ranlib ../../../../../../../ompi/mca/io/romio/.libs/libmca_io_romio.a
ar -cru ../../../../../../../ompi/.libs/libmpi.a *.o 
ranlib ../../../../../../../ompi/.libs/libmpi.a
echo "Hey.  You can just use make now"
