#! /bin/tcsh -f

set OMPI_VERSION = 1.4.3
set adio_path = ${USER}-ompi-${OMPI_VERSION}/ompi/mca/io/romio/romio/adio
set patch = ad-patches/openmpi/ompi-${OMPI_VERSION}-plfs.patch

\rm -rf /tmp/${USER}-ompi-${OMPI_VERSION}
mkdir -p $adio_path/ad_plfs
cp ad_plfs/* $adio_path/ad_plfs
/bin/cp -f $adio_path/ad_plfs/Makefile.am.ompi $adio_path/ad_plfs/Makefile.am

rm -f $patch; touch $patch
foreach file ( ad_plfs/*.[ch] ad_plfs/Makefile.am )
  echo "Creating patch for $file"
  diff -Naur openmpi-${OMPI_VERSION}/ompi/mca/io/romio/romio/adio/$file $adio_path/$file >> $patch
end
\rm -rf ${USER}-ompi-${OMPI_VERSION}

echo Your patchfile is `pwd`/$patch 
