#! /bin/tcsh -f

set OMPI_VERSION = 1.4.3
set adio_path = /tmp/${USER}-ompi-${OMPI_VERSION}/ompi/mca/io/romio/romio/adio
set patch = ad-patches/openmpi/ompi-${OMPI_VERSION}-plfs.patch

\rm -rf /tmp/${USER}-ompi-${OMPI_VERSION}
mkdir -p $adio_path
cp -rf ad_plfs $adio_path
# when make dist calls us, it first copies Makefile.am.ompi to /tmp
# if we're run independently, put it there ourselves
if ( ! -f /tmp/Makefile.am.ompi ) then
  cp ad_plfs/Makefile.am.ompi /tmp
endif
/bin/cp -f /tmp/Makefile.am.ompi $adio_path/ad_plfs/Makefile.am

rm -f $patch; touch $patch
foreach file ( ad_plfs/*.[ch] ad_plfs/Makefile.am )
  echo "Creating patch for $file"
  diff -Naur openmpi-${OMPI_VERSION}/ompi/mca/io/romio/romio/adio/$file $adio_path/$file >> $patch
end
\rm -rf /tmp/${USER}-ompi-${OMPI_VERSION}

echo Your patchfile is `pwd`/$patch 
