#! /bin/tcsh

set command = "make -k -C $HOME/Testing/plfs/trunk/fuse umount smount"
set pexec = $HOME/Testing/utilities/scripts/pexec

if ( -x $pexec ) then
    echo "Using pexec"
    set nodes = `uniq $PBS_NODEFILE | tr '\n' ','`
    echo $nodes
    $pexec -pP 32 -m $nodes --all --ssh $command |& grep -v tput
    $pexec -pP 32 -m $nodes --all --ssh cat $PLFS_MNT/.plfsdebug | grep -a Uptime 
else 
    echo "Using ssh"
    foreach node ( `uniq $PBS_NODEFILE` )
        ssh $node $command  |& grep -v tput
    end
endif
