#! /bin/tcsh

if ( ! -f ~/.plfsrc ) then
  echo "No ~/.plfsrc found"
  exit 1 
endif

set plfs   = $HOME/Testing/plfs/trunk/fuse/plfs
set mnt_pt = `awk '/^mount_point/ {print $2}' ~/.plfsrc | tail -1`
set mount  = "$plfs $mnt_pt -o direct_io" 
set pexec  = $HOME/Testing/utilities/scripts/pexec

if ( -x $pexec ) then
    echo "Using pexec"
    set nodes = `uniq $PBS_NODEFILE | tr '\n' ','`
    echo $nodes
    set pexec = "$pexec -pP 32 -m $nodes --all --ssh"
      # always try to unmount first
    $pexec fusermount -u $mnt_pt
    if ( $1 != "umount" ) then
      $pexec mkdir -p $mnt_pt 
      $pexec $mount |& grep -v tput
    endif
    $pexec grep -a Uptime $mnt_pt/.plfsdebug 
else 
    echo "No pexec executable found"
endif
